name: Notify

on:
  schedule:
    - cron: 40 11 * * * # 6:40 PM in Vietnam

jobs:
  update-data:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Python Packages
        run: |
          pip install -r requirements.txt

      - name: Notify
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
